name: Deploy Front to VPS (prod)

on:
  workflow_dispatch:
  push:
    branches:
      - main


env:
  BRANCH: main
  REACT_APP_GRAPHQL_URI: ${{ vars.PROD_REACT_APP_GRAPHQL_URI }}
  REACT_APP_URI: ${{ vars.PROD_REACT_APP_URI }}
  REACT_APP_API_TOKEN: ${{ secrets.PROD_REACT_APP_API_TOKEN }}

jobs:
  Update-server:
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes in dev server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            cd ${{ secrets.PROD_PATH_TO_DEPLOY }}
            branch=$(git rev-parse --abbrev-ref HEAD)   # chech current branch
            echo "Current branch is $branch"
            if [[ "$branch" != "${{ env.BRANCH }}" ]]; then           
              git checkout ${{ env.BRANCH }}
            fi
            git fetch --all
            git reset --hard origin/${{ env.BRANCH }}
            git pull

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd frontend
          npm install -ci

      - name: Run build task
        timeout-minutes: 5
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd frontend
          export CI=false
          npm run build

      - name: Delete previos build in server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            # cd ${{ secrets.PROD_PATH_TO_DEPLOY }}/frontend
            if [ -d '${{ secrets.PROD_PATH_TO_DEPLOY }}/frontend/build' ]; then
              echo "Build finded! EXTERMINATE!!!!"
              rm -rf ${{ secrets.PROD_PATH_TO_DEPLOY }}/frontend/build
            else
              echo "Build not exist. Continue working"
            fi

      - name: Deploy Build to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          source: 'frontend/build,frontend/public'
          target: ${{ secrets.PROD_PATH_TO_DEPLOY }}
